class news {
    constructor(_id, _text) {
        this.idx = _id;
        this.text = _text;
    }
}
const news = [
    new news("news1", "不会做增量游戏怎么办？看风灵作成的原代码一个半小时就学会了！"),
    new news("news2", "RBNR这个游戏实际上的名称是RBNR^5，因为已经重制过4次了，但是ADN一次没有重制过，很多设定从2024年就开始有了，正如懦夫在死前就已经死过好多次，勇士一生只死一次————凯撒在死二次前看了几千年后的RBNR和ADN，临终时如是说。"),
    new news("news3", "尝试用ai做了一个增量游戏，结果bug比功能多。"),
    new news("news4", "请选择你期望的实验人员。 [A]砂糖  [B]槿春  [C]阮·梅 [D]盯帧 [E]大黑塔 [F]白鞋底"),
    new news("news5", "请选择你期望的实验对象。 [A]你自己   [B]你自己"),
    new news("news6", "<img src='baixie.png' /><img src='baixie.png' /><img src='baixie.png' />"),
    new news("news7", "googology意思是“大数学”，音译为“果糕逻辑”，使用果糕逻辑这个音译名以表示内容之不严谨。"),
    new news("news8", "滚动新闻的添加速度将是毁灭性的！滚动速度也是！"),
    new news("news9", "代码组建议了一个事项，因为这样他们就只需要复制粘贴了（逃……"),
    new news("news10", "当3个人同时写代码，Bug和Conflict都将是毁灭性的，但是ADN只有一个人写代码……"),
    new news("news11", "ADN初期以平均 5 小时一次大更新的节奏稳步推进着。本来是 5 分钟一次，但是作者咕咕咕就咕到了 5 小时一次。"),
    new news("news72", "@艾斯亿诶嗯叉了叉 @哈德·刷题 @古勾儿滋滋希"),
    new news("news12", "要是 ADE 有我们这个开发速度已经到 ω 奖励了！"),
    new news("news13", "完成第 -1 层（成就）的时间等于解锁第四个同伴的时间，完成第-2层（新闻）的时间取决于写新闻代码的人添加了多少奇怪的条件"),
    new news("news14", "unicode命名法：String.fromCharCode(初始名字.charCodeAt() + n)，只有风灵作成重置层取名参考这玩意儿"),
    new news("news15", "Breaking News! 等待10秒，用代码实现Fake news!"),
    new news("news16", "AD16 mod 2 = 1"),
    new news("news17", "你知道吗？Bourgain证明了Δ(x)=O(x^517/1648+ε)结果被发现是错的，下次你做错数学题的时候想想他吧"),
    new news("news18", "@帝诶了艾斯帝诶了"),
    new news("news19", "有一颗很大的树，它指引了人们的道路，但是一开始种这棵树的时候，有一年时间没管它，树塌了，尝试重新种这棵树，当它制取荫凉的时候，树炸了"),
    new news("news20", "Cookie Clicker NG++ 竟然有C2S的内容即《中生代山谷增加糖块加成，超越增加牛奶加成》"),
    new news("news21", "扭敧是有意义的词。时间扭敧：使游戏时间非线性增长，主要作用是显著降低时间墙。"),
    new news("news22", "nanenan /'nænenən/ n.无大数js的放置/增量游戏的终局 v.玩增量游戏出现异常"),
    new news("news23", "反物质天神，是饼干点击邪恶的老奶奶，是协同放置的最后一个饼干升级，是绝对无限卵的催化剂"),
    new news("news24", "24岁，事学生，是一个一个一个"),
    new news("news25", "大冲突（Big Conflict）和大发散（Big Divergent）的下一场灾难是什么？大硬塞（Big Eingsai）"),
    new news("news26", "哈德·刷题降临 RBNR 引发大侵袭"),
    new news("news27", "滚动新闻是可以被关闭的"),
    new news("news28", "在黑暗模式下游玩游戏可以获得惊喜"),
    new news("news29", "有人说，游戏崩坏始于哈德·刷题，警惕每一个蒋小绒！真的吗？我觉得，最有发言权的应该是小绒本身！！！他的发言权应该最大，游戏崩坏只是 bug 乱飞，平衡搞砸也只是数值问题，不信你去看他的解释！https://www.luogu.me/article/k6coo91o，自己去好好看看再说话（三岁小男孩内心独白，不喜勿喷，违规紫杉）！"),
    new news("news30", "我要吃YFC（凯撒13）的大胸，小胸，翅尖，翅中，翅根，大腿，头，冠，爪，脖子，锁骨，皮，胗和心脏。喂！这里不是食堂！"),
    new news("news31", "成就是本游戏的第 -1 个层级，新闻是本游戏的第 -2 个层级，同伴是本游戏的第 -3 个层级，统计是本游戏的第 -4 个层级，设置是本游戏的第 -5 个层级，无用的回形针是本游戏的第 -6 个层级，Hyp Cos是本游戏的第 -7 个层级，一颗中子星是本游戏的第 -8 个层级"),
    new news("news32", "RBNR 曾经在乘法层级的末期有一个三重指数级别的发散，如果你看到了这条新闻，就说明这个发散已被移除了。"),
    new news("news33", "谁能把这坨东西填满"),
    new news("news34", "无限挑战 5 是一场血腥战争的最终结果"),
    new news("news35", "The first one is always <i>free</i> fake."),
    new news("news36", "不懂就问，这是病毒树吗，你再加多点升级都能堆到一天了"),
    new news("news37", "在设计初期质因数几乎一点用都没有，后来改了，但造成了发散"),
    new news("news38", "游玩 RBNR 有助于提高天文学家一颗中子星的寿命，ADN 能直接让人家永生"),
    new news("news39", "这是放置游戏，这是劝退树，更是革命空闲"),
    new news("news40", "Oni gaming在时间墙大赛中获得了第二名，第一名是RBNR"),
    new news("news75", "ADFaster在时间墙小赛（越短越好）中获得了第二名，第一名是ADN"),
    new news("news73", "Oni gaming在逼氪大赛中获得了第一名"),
    new news("news76", "逼氪大赛中因为并列倒数第一太多，取消了倒数第一的安慰奖"),
    new news("news41", "反物质维度层级曾经延伸到了2<sup>1024</sup>这么大的数字"),
    new news("news42", "黑塔女士举世无双！黑塔女士聪明绝顶！黑塔女士沉鱼落雁！钥落千星，才震银宇，难描绝美，短言难述…解弧波算法之真谛，造模拟宇宙为真知，虚构难藏实之魅力，真伪何妨追随与否，此刻……黑门永存！"),
    new news("news74", "大黑举世无双！大黑聪明绝顶！大黑沉鱼落雁！钥落Q群，才震群友，难描作品，短言难述…解增量游戏之真谛，造PEIT为真知，禁言难藏增量魅力，模组何妨树状与否，此刻……大黑永存！"),
    new news("news43", "<b>大机罢</b>"),
    new news("news44", "oiiaiioiiaii __猫__ oiiaiioiiaii __猫__ oiiaiioiiaii __猫__ oiiaiioiiaii __猫__ "),
    new news("news46", "不幸的是我们用完了滚动新闻的梗，只能让你看这段话了"),
    new news("news47", "新闻对我来说是增量游戏聚集地(在梗文字中发现了少量增量游戏)"),
    new news("news48", "两个人同时修复一个bug导致bug又回来了，要三个人同时修复才能修好这个bug，ω个人同时修复一个bug导致bug又回来了，要ω+1个人同时修复才能修好这个bug——在经哈德·刷题采访时，一颗中子星如是说。"),
    new news("news49", "求树的高度的方法：三角函数，深度优先搜索，googology，线段树（逃）"),
    new news("news50", "亲爱的玩家，当你玩ADN的时候，要记得是天文学家EdenGameMaster帮你削弱了巨额的时间墙。如若没有EdenGameMaster的努力，你达到指数层至少需要<del>1.79e308</del>1无限（已达一重大脆）秒抵达指数层"),
    new news("news51", "既然IMR有软上限，溢出，淤积，为什么ADN不出现这些机制？ADN没有时间墙，拖膨胀的办法也只有软上限，真是新手的增量福音。"),
    new news("news52", "前面忘了，中间忘了，后面也忘了……这项目干啥来着？——在被哈德采访的时候，RBNR 制作组艾奇说。"),
    new news("news53", "史上平衡最差的增量游戏是什么？IMR IDR WSC MDVI 算什么，RBNR 才是真神！——哈德·刷题"),
    new news("news54", "Vorona言：antiest-booster gainest"),
    new news("news55", "这个人不在人员名单上，但他有自爆果汁，所以他是科学家人员"),
    new news("news56", "请问这个黄豆双手向下跪地是什么意思？"),
    new news("news57", "[暂不支持该消息类型，请用 [暂不支持该消息类型，请用 ...... 查看] 查看]"),
    new news("news58", "这公司不实在，买的软盘正面写着3M，背面写的却是1.44M，格式化完只有1.38M，就像别看这东西打折完要卖两三万，打折前只卖一百三。"),
    new news("news59", "本次你连续1.1981F7次掷十面骰出现1，你看到这句话的概率是1/1.1981F8，也就是1/1.1981F8%"),
    new news("news60", "本游戏的终局不是在加强疫苗中到达1.1981F7数值"),
    new news("news61", "你还记得看到的上一条新闻是什么吗"),
    new news("news62", "我们的留言板上写着指数层级早已前瞻完成，但你猜真的完成了吗"),
    new news("news63", "什么？你问我们没事干的时候干什么？我们RBNR制作组没有没事干的时候"),
    new news("news64", "发散是反时间墙，时间墙是反发散，既不发散又不时间墙是正常的，既发散又时间墙是增量游戏作者故意设计的"),
    new news("news65", "在无人在意的角落，又有一个新闻诞生了"),
    new news("news66", "由于光速ADN更新（4L in 15d)造成了过大的debuff，致使开发者哈德·刷题写出一堆bug"),
    new news("news67", "新闻生成失败：反问题尺寸"),
    new news("news68", "幼儿园平均年龄三十七，我妈年龄三十七，是不是在上幼儿园"),
    new news("news69", "一颗中子星是中子星爆炸蹦出来的天才少年/天才少女吗，这么会画大饼，比哈德还会画"),
    new news("news70", "哈德·刷题，2023-9-10~2025-8-3，享年 1 岁"),
    new news("news71", ""),
]